name: Lint files

on:
  push:
    branches:
      - '**'

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.17.0

      # ESLint and Prettier must be in `package.json`
      - name: Install dependencies
        run: yarn

      - name: Run linters
        uses: wearerequired/lint-action@v1
        with:
          eslint: true
          stylelint: true
